const categoryController = require('./../controllers/categoryConfig');
const express = require('express');
const router = express.Router();
const category_thumbnails = require('../middleware/uploadMidleWare');
const venue_images = require('../middleware/uploadVenueMiddleWare');
router.post('/add-category', category_thumbnails.single('image'), categoryController.createCategoryConfig);
router.get('/categories', categoryController.getAllCategoryConfigs);
router.post('/add-venue', categoryController.createVenues);
router.post('/add-jewellery', categoryController.createJewellery);
router.post('/add-photographer', categoryController.createPhotographer);
router.post('/getvenues', categoryController.getVenuesByCategoryId);
router.post('/getjewelleries', categoryController.getJewelleryByCategoryId);
router.post('/upload-venue-image', venue_images.single('image'), categoryController.uploadVenueImage);
module.exports = router;