export const physicalExamConfigDescription = {
  "MILD_DISTRESS": "Mild Distress",
  "MODERATE_DISTRESS": "Moderate Distress",
  "SIGNIFICANT_DISTRESS": "Significant Distress",
  "PROFOUND_DISTRESS": "Profound Distress",
  "NO": "No",
  "MODERATE_ILL": "Appears Moderately ill",
  "ACTIVELY_ILL": "Actively ill",
  "IN_EXTREMIS": "In Extremis",
  "STATED_AGE": "Appears Stated Age",
  "OLDER_AGE": "Appears Older than Stated Age",
  "YOUNGER_AGE": "Appears younger than Stated Age",
  "WARM_DRY": "Warm dry Color",
  "FEELS_HOT": "Feels Hot",
  "FLUSHED_PALE": "Flushed Pale",
  "DIAPHORETIC": "Diaphoretic",
  "CYANOTIC": "Cyanotic",
  "COOL": "Cool",
  "ASHEN": "Ashen",
  "MOTTLED": "Mottled",
  "NORMAL_HABITS": "Normal",
  "OBESE": "Obese",
  "CACHETIC": "Cachetic",
  "DEBILITATED": "Debilitated",
  "FAILURE_TO_THRIVE": "Failure to Thrive",
  "POOR_HYGIENE": "Poor Hygiene",
  "ALERT_AND_APPROPRIATE": "Alert and Appropriate",
  "CONFUSED": "Confused",
  "INTOXICATED": "Intoxicated",
  "ANXIOUS": "Anxious",
  "ANGRY": "Angry",
  "VERBALLY_ABUSIVE": "Verbally Abusive",
  "TEARFUL": "Tearful",
  "OTHER": "Other",
  "HYDRATED": "Hydrated",
  "DRY_MUCOSAL_MEMBRANES": "Dry Mucous Membranes",
  "POOR_SKIN_TURGOR": "Poor Skin Turgor",
  "ALCOHOL_ON_BREATH": "Alcohol on Breath",
  "MENTAL_RETARDATION": "Mental Retardation",
  "DEMENTED": "Demented",
  "CONTRACTURES": "Contractures",
  "URINARY_CATHETER": "Urinary Catheter",
  "DIAPERS": "Diapers",
  "G_TUBE": "G-Tube",
  "DECUBITUS": "Decubitus",
  "NON_AMBULATORY": "Non Ambulatory",
  "MOIST_NO_PETECHIAE": "Moist - No Petechiae",
  "THRUSH": "Thrush",
  "PETECHIAE": "Petechiae",
  "TRAUMA": "Trauma",
  "NORMAL_POSTERIOR_PHARYNX": "Normal",
  "LARGE_TONSILS": "Large Tonsils",
  "PHARYNGITIS": "Pharyngitis",
  "TONSILITIS": "Tonsilitis",
  "POST_NASAL_DRIP": "Post nasal drip",
  "EDEMA_UVULA": "Edema of Uvula",
  "FOREIGN_BODY": "Foreign body exam",
  "PERITONSILLAR_ABSCESS": "Peritonsillar Abscess",
  "NORMAL_VOICE": "Normal",
  "HOARSE": "Hoarse",
  "NASAL_STUFFY_VOICE": "Nasal Stuffy Voice",
  "WHISPERED": "Whispered",
  "APHONIA": "Aphonia",
  "USES_ELECTRONIC_DEVICE": "Uses Electronic voice Synthesizer laryngectomy",
  "GAG_REFLEX_INTACT": "Gag Reflex Intact",
  "POOR_GAG_REFLEX": "Poor Gag Reflex",
  "ABSENT_GAG_REFLEX": "Absent Gag Reflex",
  "SWALLOWING_WELL": "Swallowing Well",
  "NO_PROBLEMS_WITH_SECRETIONS": "No Problems With Secretions",
  "POOR_SWALLOWING_WITH_CHOKING": "Poor Swallowing With Choking",
  "DROOLING": "Drooling",
  "HANDLING_SECRETIONS_POORLY": "Handling Secretions Poorly",
  "NORMAL_GUMS_TEETH": "Normal Dentures",
  "ABNORMAL_GUMS": "Abnormal Gums - Canker Sores - Ulcers etc",
  "GENERALIZED_TOOTH_PROBLEMS": "Generalized Tooth Problems",
  "LOCAL_DENTAL_ABSCESS": "Local Dental Abscess",
  "NORMAL_MUCOSA_SALIVARY_GLANDS": "Normal",
  "HAND_MOUTH_FOOT_DISE": "Hand, Mouth, Foot Disease",
  "ABNORMAL_ULCERATIONS_INFLAMMATION_BLOCKED_SALIVARY_DUCT": "Abnormal -Ulcerations - Inflammation - Blocked Salivary Duct",
  "NORMAL_EVALUATION_HEARING": "Normal",
  "HEARING_AID": "Hearing Aid",
  "DEAF": "Deaf",
  "DOCUMENT_AUDIOMETRY": "Hearing Problems",
  "NORMAL_EXAM": "Normal External Exam",
  "NORMAL_CANAL_EXAM": "Normal External Canal",
  "NORMAL_EARDRUM": "Normal Eardrum",
  "ABNORMAL_EAR_EXAM": "Abnormal",
  "NO_RHINITIS": "No Rhinitis",
  "EPISTAXIS": "Epistaxis",
  "ABNORMAL_NOSE_SINUSES": "Abnormal",
  "NORMOCEPHALIC": "Normocephalic",
  "SP_CRANIOTOMY": "S/P Craniotomy",
  "DYSMORPHIC_FEATURES": "Dysmorphic Features",
  "CUSHINGOID_FACIES": "Cushingoid Facies",
  "SUPPLE": "Supple",
  "NO_ADENOPATHY": "No Adenopathy",
  "STIFF_NECK": "Stiff Neck",
  "PALPABLE_THYROID": "Palpable Thyroid",
  "ADENOPATHY": "Adenopathy",
  "JUGULAR_VENOUS_DISTENSION": "Jugular Venous Distension",
  "CAROTID_BRUIT": "Carotid Bruit",
  "NONE": "None",
  "HEALING_SURGICAL_INCSN": "Healing Surgical Incision",
  "TRACHEOSTOMY_OTHER": "Tracheostomy - Other Surgery",
  "ALLERGIC_CONJUNCTIVITIS": "Allergic Conjunctivitis",
  "CORNEAL_FOREIGN_BODY": "Corneal Foreign Body",
  "SIMPLE_EXAM": "Simple Exam",
  "SLIT_LAMP": "Slit Lamp",
  "TONOMETER": "Tonometer",
  "FLUORESCEIN": "Fluorescein",
  "SEE_CHART": "See Chart",
  "UNABLE_TO_GET_ADEQUATE_EXAM": "Unable to get adequate exam",
  "NOT_DONE": "Not Done",
  "ENTER_ACUITY_HERE": "Enter acuity here",
  "NORMAL_COLOR_VISION": "Normal Color vision",
  "ABNORMAL_COLOR_VISION": "Abnormal Color vision",
  "YES": "Yes",
  "NORMAL_GLOBE_EXOPHTHALMOS_ARTIFICIAL_EYE": "Normal",
  "ABNORMAL_ARTIFICIAL_EYE": "Abnormal",
  "NORMAL_EYELIDS": "Normal",
  "LID_EVERTED": "Lid Everted - Normal",
  "GENERAL_FINDINGS": "General Findings",
  "LOCAL_ABNORMALITIES": "Local ABN",
  "NORMAL_CONJUNCTIVA_SCLERA": "Normal",
  "NORMAL_CORNEA": "Normal",
  "ARCUS_SENILIS": "Arcus Senilis",
  "OTHER_ABNORMALITIES": "Other Abnormalities",
  "NORMAL_ANTERIOR_CHAMBER": "Normal",
  "ABNORMAL_BLOOD_OPACITY": "Abnormal - Blood - Opacity- Cataracts etc",
  "NORMAL_PUPILS": "Normal",
  "PUPILS_SP_CATARACT_EXTRACTION": "S/p Cataract Extraction",
  "PUPILS_OTHER_ABNORMALITIES": "Other Abnormalities",
  "NORMAL_RETINA": "Normal",
  "RETINA_SHARP_OPTIC_DISK": "Sharp Optic Disk",
  "RETINA_GOOD_VENOUS_PULSATION": "Good Venous Pulsation",
  "RETINA_POORLY_VISUALIZED": "Poorly Visualized",
  "RETINA_NOT_VISUALIZED": "Not Visualized",
  "RETINA_EXAM_ABNORMAL": "Abnormal",
  "NORMAL_EXTRA_OCULAR_MOVEMENTS": "Normal",
  "ABNORMAL_EXTRA_OCULAR_MOVEMENTS": "Abnormal",
  "GROSSLY_NORMAL_PERIPHERAL_VISION": "Grossly Normal",
  "ABNORMAL_PERIPHERAL_VISION": "Visual Field Cut",
  "TUNNEL_VISION": "Tunnel Vision",
  "NO_ACUTE_RESPIRATORY_DISTRESS": "No Acute Respiratory Distress",
  "HAS_RESPIRATORY_DISTRESS": "Has Respiratory Distress",
  "RESPIRATORY_RATE_NORMAL": "Normal",
  "RESPIRATORY_RATE_SECONDARY": "Secondary Hyperventilation",
  "RESPIRATORY_RATE_TRUE_TACHYPNEA": "True Tachypnea",
  "RESPIRATORY_RATE_SNORING": "Snoring Respirations",
  "RESPIRATORY_RATE_POOR": "Poor Respiratory Effort",
  "ON_ROOM_AIR": "On Room Air",
  "RECEIVING_OXYGEN": "Receiving Oxygen",
  "MIDLINE_TRACHEA": "Midline Trachea",
  "TRACHEA_DEVIATED_TO_ONE_SIDE": "Trachea deviated to one side",
  "PATIENT_HAS_A_TRACHEOSTOMY": "Patient has a tracheostomy",
  "NO_STRIDOR": "No Stridor",
  "HAS_STRIDOR": "Has Stridulous Breath Sounds",
  "NO_COUGH": "No Cough",
  "HAS_COUGH": "Has a Cough",
  "LUNGS_CLEAR": "Lungs Clear",
  "HAS_BI_BASILAR_FINDINGS": "Has Bi-Basilar Findings",
  "HAS_GENERALIZED_FINDINGS": "Has generalized Findings",
  "NONE_LOCALIZED_FINDINS_CHEST_EXAM": "None",
  "HAS_LOCALIZED_FINDINGS_CHEST_EXAM": "Has Localized Findings",
  "NORMAL_BREAST_EXAM": "Normal",
  "ABNORMAL_BREAST_EXAM": "Abnormal breast exam",
  "NORMAL_PRECORDIUM": "Normal",
  "PRECORDIAL_HEAVE": "Precordial heave",
  "PECTUS_EXCAVATUM": "Pectus excavatum",
  "REGULAR_RATE_RHYTHM": "Regular rate and rhythm",
  "ABNORMAL_RATE_RHYTHM": "Abnormality",
  "NORMAL_HEART_SOUNDS": "Normal",
  "DISTANT": "Distant",
  "MECHANICAL_VALVE": "Mechanical Valve",
  "ABSENT": "Absent",
  "NO_MURMUR": "No murmurs or rubs",
  "CARDIAC_MURMUR_RUBS": "Cardiac Murmurs and Rubs",
  "NONE_GALLOPS_EXTRA_SOUNDS": "None",
  "S3_GALLOP": "S3 gallop",
  "S4_GALLOP": "S4 gallop",
  "OPENING_SNAP": "Opening snap",
  "ABNORMAL_S2": "Abnormal S2 does not vary with respiration",
  "DIASTOLIC_CLICK": "Diastolic click",
  "NORMAL_CHEST_WALL": "Normal",
  "LOCAL_TENDERNESS_CHEST_WALL": "Local tenderness/pain or other chest wall findings",
  "NO_JVD": "No JVD",
  "NO_CAROTID_BRUIT": "No Carotid bruit",
  "ELEVATED_JVD": "Elevated JVD",
  "HAS_CAROTID_BRUIT": "Has Carotid bruit",
  "RADIAL_EQUAL": "Radial pulses equal",
  "BP_EQUAL": "BP equal both Arms",
  "ABNORMAL_OR_EXTENDED": "Abnormal or Extended documentation",
  "NO_PEDAL_EDEMA": "No pedal edema",
  "NO_CALF_TENDERNESS": "No calf tenderness",
  "TRACE_EDEMA": "Trace pedal edema",
  "POS_PEDAL_EDEMA": "+ pedal edema",
  "EXTENDED_EXAM": "Extended EXTREMITY EXAM",
  "NONE_PREVIOUS_CHEST_SURGERIES": "None",
  "STERNOTOMY_SCAR": "Sternotomy scar",
  "THORACOTOMY_SCAR": "Thoracotomy scar",
  "OLD_CHEST_SCAR": "Old chest scar",
  "CHEST_TUBE": "Chest tube",
  "HEALING_CHEST_WOUND": "Healing chest wound",
  "PACEMAKER": "Permanent pacemaker",
  "AICD": "AICD",
  "SUBQ_MEDIPORT": "Subcutaneous Mediport",
  "DIALYSIS_CATHETER": "Dialysis catheter",
  "CENTRAL_ACCESS": "Other central venous access",
  "NORMAL_GENERAL_OBSERVATION_OF_ABDOMEN": "Normal",
  "DISTENDED": "Distended",
  "CW_ASCITES": "c/w Ascites",
  "CACHECTIC": "Cachectic",
  "NOTHING_UNUSUAL": "Nothing unusual",
  "TUBE_DRAIN": "Tube or Surgical drain",
  "NORMAL_AUSCULTATION_OF_ABDOMEN": "Normal",
  "HYPERACTIVE": "Hyperactive",
  "HYPOACTIVE": "Hypoactive",
  "TINKLING": "Tinkling",
  "INTERMITTENT": "Intermittent",
  "NO_BRUIT": "No bruit",
  "BRUIT": "Bruit",
  "NORMAL_PALPATION_OF_ABDOMEN": "Normal",
  "LOCALIZED_FINDINGS": "Localized findings",
  "UPPER_ABD_FINDINGS": "General Upper abd findings",
  "LOWER_ABD_FINDINGS": "General Lower abd findings",
  "GENERALIZED_FINDINGS": "Generalized findings",
  "NO_TROUBLE_SWALLOWING": "No trouble swallowing",
  "TROUBLE_WITH_SOLIDS": "Trouble w/ solids",
  "TROUBLE_WITH_LIQUIDS_SOLIDS": "Trouble w/ Liquids and Solids",
  "CANT_SWALLOW": "Can't swallow anything (comes right back)",
  "NORMAL_RECTAL_EXAM": "Normal",
  "ABNORMAL_RECTAL_EXAM": "Abnormal",
  "RECTAL_DEFERRED": "Rectal deferred",
  "DOCUMENT_HEME_STATUS": "Describe stool and document heme status",
  "NONE_HERNIAS": "None",
  "HAS_HERNIA": "Has a hernia",
  "NONE_PREVIOUS_ABDOMINAL_SURGERIES": "None",
  "HEALING_WOUND": "Healing abdominal wound",
  "OLD_SCAR": "Old abdominal scar",
  "URETHRAL_DISCHARGE": "Urethral discharge",
  "NORMAL_INGUINAL_AREA": "Normal",
  "PEDICULOSIS": "Pediculosis",
  "FUNGAL_INFLAMMATION": "Fungal inflammation",
  "HERNIA": "Hernia",
  "TENDER_INGUINAL_LIGAMENT": "Tender Inguinal ligament - Strain",
  "NO_EVIDENCE_TRAUMA": "No evidence of trauma",
  "POSITIVE_TRAUMA": "Positive trauma",
  "CIRCUMCISED": "Circumcised",
  "UNCIRCUMCISED": "Uncircumcised",
  "BALANITIS": "Balanitis",
  "PHIMOSIS": "Phimosis",
  "EDEMA": "Edema",
  "PARAPHIMOSIS_OR_RING": "Paraphimosis or Penile ring",
  "HYPOSPADIAS": "Hypospadias",
  "BALANITIS_NON_SPECIFIC": "Balanitis - non specific",
  "BALANITIS_CANDIDA": "Balanitis - presumptive candida",
  "NORMAL_PENILE_SHAFT": "Normal",
  "ULCER_OF_SHAFT": "Isolated ulcer of shaft",
  "HERPETIC_LESIONS": "Herpetic lesions",
  "URTICARIAL_RASH": "Urticarial rash",
  "VENERAL_WARTS": "Venereal warts",
  "PRIAPISM": "Priapism",
  "FRACTURED_PENIS": "Fractured penis",
  "NORMAL_TESTICULAR_EXAM": "Normal",
  "COMPLETE_EXAM": "Complete exam",
  "HEMORRHOIDS": "Hemorrhoids",
  "GUAIAC_STATUS": "Guaiac status",
  "PROSTATE_PROBLEM": "Prostate problem",
  "NONE_SURGICAL_SCARS": "None",
  "SP_ORCHIECTOMY": "S/P orchiectomy",
  "PENILE_IMPLANT": "Penile implant",
  "NORMAL_MENTAL_STATUS": "Normal",
  "MINI_MENTAL_EXAM": "Mini Mental Status exam",
  "ABNORMAL_MENTAL_STATUS": "Abnormal",
  "PERFORM_GCS": "Perform GCS",
  "CIWA_ASSESSMENT": "CIWA - Clinical Institute Withdrawal Assessment",
  "NORMAL_SPEECH_AND_VOCALIZATION": "Normal",
  "ABNORMAL_SPEECH_AND_VOCALIZATION": "Abnormal",
  "NORMAL_CRANIAL_NERVES": "Normal",
  "ABNORMAL_CRANIAL_NERVES": "Abnormal",
  "BELLS_PALSY": "Classic Bells Palsy",
  "NORMAL_PUPILS_LIGHT_REACTIVITY": "Normal",
  "ABNORMAL_PUPILS_LIGHT_REACTIVITY": "Abnormal",
  "NORMAL_MUSCLE_STRENGTH_TONE": "Normal",
  "ABNORMAL_MUSCLE_STRENGTH_TONE": "Abnormal",
  "CANT_EVALUATE_MUSCLE": "Can't reliably evaluate",
  "NORMAL_SENSORY_EXAM": "Normal",
  "ABNORMAL_SENSORY_EXAM": "Abnormal",
  "CANT_EVALUATE_SENSORY": "Can't reliably evaluate",
  "NORMAL_REFLEXES": "Normal",
  "ABNORMAL_REFLEXES": "Abnormal",
  "NORMAL_GAIT_BODY_CONTROL": "Normal",
  "ABNORMAL_GAIT_BODY_CONTROL": "Abnormal",
  "NOT_TESTED_GAIT": "Not tested",
  "NORMAL_CEREBELLAR_FUNCTION": "Normal",
  "ABNORMAL_CEREBELLAR_FUNCTION": "Abnormal",
  "NORMAL_MOVEMENT": "Normal",
  "ABNORMAL_MOVEMENT": "Abnormal",
  "NEUROSURGICAL_QUICK_EXAM": "Neurosurgical Quick Exam Screening",
  "GOOD_OVERALL_COLOR": "Good",
  "PALE": "Pale",
  "FLUSHED": "Flushed",
  "JAUNDICED": "Jaundiced",
  "DUSKY": "Dusky",
  "PATIENT_IS_BLACK": "Patient is black",
  "GOOD_CAPILLARY_REFILL": "Good capillary refill",
  "DELAYED_CAPILLARY_REFILL": "Delayed capillary refill",
  "POOR_CIRCULATION": "Poor circulation - Stasis - Ulceration - Edema - etc.",
  "WARM": "Warm",
  "COLD": "Cold",
  "HOT": "Hot",
  "DRY": "Dry",
  "MOIST": "Moist",
  "SMOOTH": "Smooth",
  "ROUGH": "Rough",
  "CRACKED": "Cracked",
  "SCALING": "Scaling",
  "NONE_RASH": "None",
  "LOCALIZED_RASH": "Localized rash or inflammation",
  "GENERALIZED_RASH": "Generalized rash or inflammation",
  "NO_PETECHIA": "No petechia",
  "HAS_PETECHIA": "Has petechia (either localized or generalized)",
  "NORMAL_ELASTICITY": "Normal",
  "TENTING": "Tenting (c/w dehydration)",
  "SENILE_LOSS": "Senile loss of elasticity",
  "ATROPHIC_THIN_SKIN": "Atrophic thin 'parchment' like skin",
  "SENILE_PURPURA": "Senile purpura",
  "SENILE_KERATOSIS": "Senile keratosis",
  "NONE_GENERALIZED_EXAM": "None",
  "HAS_PIGMENTARY_CHANGES": "Has generalized Pigmentary changes",
  "MULTIPLE_TATTOOS": "Multiple Tattoos",
  "MISCELLANEOUS_FREE_TEXT": "Miscellaneous - Free text",
  "NORMAL_CERVICAL_LYMPH_NODES": "Normal",
  "ABNORMAL_CERVICAL_LYMPH_NODES": "Abnormal",
  "NORMAL_AXILLARY_LYMPH_NODES": "Normal",
  "ABNORMAL_AXILLARY_LYMPH_NODES": "Abnormal",
  "NORMAL_EPITROCHLEAR_LYMPH_NODES": "Normal",
  "ABNORMAL_EPITROCHLEAR_LYMPH_NODES": "Abnormal",
  "NORMAL_SPLEEN": "Normal",
  "ABNORMAL_SPLEEN": "Abnormal",
  "NORMAL_INGUINAL_LYMPH_NODES": "Normal",
  "ABNORMAL_INGUINAL_LYMPH_NODES": "Abnormal",
  "WELL_KEPT": "Well kept",
  "TEARFUL_UPSET": "Tearful/Upset",
  "DISHEVELED": "Disheveled",
  "APPEARS_INTOXICATED": "Appears intoxicated",
  "IN_RESTRAINTS": "In restraints",
  "NORMAL_GENERAL_INTERACTION": "Normal personal interaction",
  "CO_OPERATIVE": "Co-operative",
  "UNCOOPERATIVE": "Un-cooperative",
  "POOR_EYE_CONTACT": "Poor eye contact",
  "NON_COMMUNICATIVE": "Non-communicative",
  "NORMAL_SPEECH_PATTERN": "Normal rate volume and coherence",
  "ABNORMAL_SPEECH_PATTERN": "Abnormal",
  "LOGICAL_ASSOCIATIONS": "Logical associations normal reasoning",
  "ABNORMAL_THOUGHT_PROCESSES": "Abnormal",
  "INTACT_REASONABLE": "Intact reasonable association of ideas",
  "LOOSE_ASSOCIATION": "Loose association",
  "TANGENTIAL": "Tangential associations",
  "CIRCUMSTANTIAL": "Circumstantial associations",
  "NONE_PSYCHOTIC_IDEATION": "None",
  "SUICIDAL": "Suicidal",
  "HALLUCINATIONS": "Hallucinations",
  "DELUSIONS": "Delusions",
  "PARANOIA": "Paranoia",
  "PREOCCUPATION_WITH_VIOLENCE": "Preoccupation with violence",
  "GOOD_JUDGMENT": "Good",
  "POOR_JUDGMENT_JOB": "Poor judgment re: Job",
  "POOR_JUDGMENT_FRIENDS": "Poor judgment re: Friends",
  "POOR_JUDGMENT_FAMILY": "Poor judgment re: Family",
  "POOR_JUDGMENT_OTHER": "Poor judgment re: Other",
  "UNABLE_TO_EVALUATE_JUDGMENT": "Unable to fully evaluate",
  "NORMAL_ORIENTATION": "Normal X 3",
  "NOT_FULLY_ORIENTED": "Not fully oriented",
  "UNABLE_TO_EVALUATE_ORIENTATION": "Unable to fully evaluate",
  "NORMAL_MEMORY": "Normal",
  "POOR_RECENT_MEMORY": "Poor recent memory",
  "POOR_REMOTE_MEMORY": "Poor remote memory",
  "UNABLE_TO_EVALUATE_MEMORY": "Unable to fully evaluate",
  "NORMAL_ATTENTION_SPAN": "Normal",
  "BRIEF": "Brief",
  "UNABLE_TO_CONCENTRATE": "Unable to concentrate on a task or conversation",
  "UNABLE_TO_EVALUATE_ATTENTION": "Unable to fully evaluate",
  "NORMAL_LANGUAGE_USE": "Normal recognition of persons and objects",
  "CONFUSION": "Confusion",
  "UNABLE_TO_EVALUATE_LANGUAGE": "Unable to fully evaluate",
  "ADEQUATE_IMPULSE_CONTROL": "Appears to have adequate control of impulses",
  "INADEQUATE_IMPULSE_CONTROL": "Poor or inadequate impulse control...",
  "NORMAL_MOOD_AFFECT": "Normal",
  "FLAT": "Flat",
  "DEPRESSED": "Depressed",
  "AGITATED": "Agitated",
  "HYPOMANIC": "Hypomanic",
  "LABILE": "Labile",
  "OTHER_MOOD": "Other-free text...",
  "NORMAL_MUSCULOSKELETAL_EXAM": "Normal strength tone and gait",
  "ABNORMAL_MUSCLE_EXAM": "Abnormal muscle exam",
  "WADDELL_SIGNS": "Document Waddell Signs for Back",
  "ABNORMAL_GAIT": "Abnormal gait"
};
